# -*- coding: utf-8 -*-
"""Task 23.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B6tlTJFKu7TRnzcCYqUKpqVnGP_FOUr5
"""

import pandas as pd

from google.colab import files

uploaded = files.upload()

df = pd.read_csv('Cricket Test Match Data.csv')

df

#Renaming Multiple Columns

df = df.rename(columns={'NO': 'Not_Cuts', 'HS': 'Highest_Time_Score', "Mat":"Matches", 'BF':"Ball_faced", "SR":"Betting_Strike_Rate"})

df.head()

#Check for null values

df.isnull().any()

df[df['Ball_faced'].isnull()==1]

df["Betting_Strike_Rate"] = df["Betting_Strike_Rate"].fillna(0)

df[df["Player"]== 'CL Walcott (WI)']

df.duplicated()

df[df['Player'].duplicated()==1]

df[df['Player'].isin(['GA Headley (WI)', 'GS Sobers (WI)','JB Hobbs (ENG)','V Sehwag (ICC/IND)'])]

df=df.drop_duplicates()

df[df['Player'].isin(['GA Headley (WI)', 'GS Sobers (WI)','JB Hobbs (ENG)','V Sehwag (ICC/IND)'])]

df['Span'].str.split(pat='-')

df['Rookie_Year'] = df["Span"].str.split(pat='-').str[0]

df['Last_Year'] = df["Span"].str.split(pat='-').str[1]

df = df.drop(['Span'], axis = 1)

df.head()

df['Player'].str.split(pat='(')

df['Country'] = df ["Player"].str.split(pat='(').str[1]
df["Country"]

df['Country'] = df['Country'].str.replace(')','')
df['Ball_faced'] = df['Ball_faced'].str.replace('+','')
df['Player'] = df ["Player"].str.split(pat='(').str[0]

df.head()

df.dtypes

df['Highest_Time_Score'] = df['Highest_Time_Score'].str.replace('*','')
df['Highest_Time_Score'] = df['Highest_Time_Score'].astype(int)

df= df.astype({'Rookie_Year':'int', "Last_Year":'int'})

df["Ball_faced"]

df.dtypes

df['Matches'] = df['Matches'].astype(int)
# df['Ball_faced'] = df['Ball_faced'].astype(int)
df['Betting_Strike_Rate'] = df['Betting_Strike_Rate'].astype(float)

df.dtypes

df["Career_Lenght"] = df["Last_Year"]-df["Rookie_Year"]

df['Career_Lenght'].mean()

df[df['Career_Lenght']>10]["Betting_Strike_Rate"].mean()

df[df["Rookie_Year"]<1960].count()

df.groupby('Country')['Highest_Time_Score'].max().reset_index().sort_values("Highest_Time_Score", ascending=False)

df.groupby('Country')[['100','50','0']].mean()

### TASK 24 USING TASK 23 DATA



df.shape

df.head()

df.columns

#Every column is a series and every series has a type
df.dtypes

df.describe()

# Step 2 : Data Preparation

df.head()

df.columns

df = df[['Player', 'Matches', 'Inns', 'Not_Cuts', 'Runs', 'Highest_Time_Score',
       'Ave', 'Ball_faced', 'Betting_Strike_Rate', '100', '50', '0', '4s',
       '6s', 'Rookie_Year', 'Last_Year', 'Country']].copy()

df.isna()

df.duplicated()

#Step 3 : Feature Understanding - univariate analysis

df['Player'].value_counts()

tp= df['Player'].value_counts().head(10).plot(kind='bar', title='Top 10 Players')
tp.set_xlabel('Player')
tp.set_ylabel('Count')

df['100'].plot(kind='hist', bins=20)

#Step 4 : Feature Relationship

df.plot(kind='scatter', x='100', y='50', title='Players 100 vs 50')

sns.scatterplot(x='100', y='50', data=df)

sns.pairplot(df, vars=["100", "50"], hue='100')

plt.show()

df.head()

df_corr = df[['100', '50']].dropna().corr()
df_corr

sns.heatmap(df_corr, annot=True)

#Step 5 : Ask question about the data
df.groupby('Player')[['100','50','0']].mean()